name: testing

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-22.04
    name: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: test
        run: go test ./...
